# Site settings
title: AAAA DALI 2016 - Data Learning and Inference
venue: Sestri Levante, Italy
permalink: "/:categories/:title.html"
banner: sestri.jpeg
conference:
  hosts:
  general:
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  workshop:
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  symposium:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  local:
  - name: Lorenzo Rosasco
    url: "http://web.mit.edu/lrosasco/www/"
    institute: University of Genova and MIT
  assistants:
  - name: Carlo Ciliberto
    url: "https://it.linkedin.com/in/carlo-ciliberto-174a98105"
    institute: IIT and MIT
  - name: Sabrina Nepozitek
    url: "http://www.da.inf.ethz.ch/people/SabrinaNepozitek/"
    institute: ETH Zurich
  steering:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hofmann
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - name: Bernhard Schölkopf (chair)
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2016 - Data Learning and Inference
  location: Sestri Levante, Italy
  year: 2016
  month: March
  dates:
  - 2016-03-30
  - 2016-03-31
  - 2016-04-01
  draft: False # set to True if the programme is draft only.
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
    url: "http://learning-systems.org/"
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
youtube:
  height: 315
  width: 560
twitter_username: 
github_username:  dalimeeting
future: true

# Build settings
markdown: kramdown
